load("@rules_jvm//:jvm.bzl", "jvm_library", "resourcegroup")

resourcegroup(
  name = "fxpro-broker_resources",
  srcs = glob(["resources/**/*"]),
  strip_prefix = "resources"
)

jvm_library(
  name = "fxpro-broker",
  module_name = "intellij.fxpro.broker",
  visibility = ["//visibility:public"],
  srcs = glob(["src/**/*.kt", "src/**/*.java", "src/**/*.form"], allow_empty = True),
  resources = [":fxpro-broker_resources"],
  deps = [
    "//platform/platform-api:ide",
    "//platform/platform-impl:ide-impl",
    "//platform/ui.jcef",
    "//platform/core-api:core",
    "//platform/util",
    "@lib//:kotlin-stdlib",
  ]
)
